### ISSUE TITLE
How to use atreugo router to work with fasthttp server

### ISSUE THREAD

**Issue by dhiemaz** [atreugo/examples#5]
I have code setup server using fasthttp server and I am using fasthttprouter as router. How can I use atreugo for the routing only to work with my fasthttp server ?

```
type server struct {
	http 	*fasthttp.Server
	router  *atreugo.Router
}

// StartServer : start HTTP Server
func Start(router *atreugo.Router) {
	var wg sync.WaitGroup

	// create new instance server
	server := newServer(router)

	// run server
	server.Run(&wg)
	wg.Wait()
}

// newServer : creates instance server
func newServer(router *atreugo.Router) *server {
	// create handler from router
	handler := router.

	// define fasthttp server
	return &server{
		http: newHTTPServer(handler),
		router:     router,
	}
}

// newHTTPServer creates a new HTTP Server
func newHTTPServer(h atreugo.Router) *fasthttp.Server {
	return &fasthttp.Server{
		Handler:     h. // ??? how to convert atreugo.Router into handler (fasthttp)
		ReduceMemoryUsage:    true,
	}
}
```

**Comment by savsgio** [comment]
Hi @dhiemaz,

Sorry for delayed answer!

You couldn't use it as a router, because it's a framework and not a router library.
So you could use Atreugo directly, because it's build on top of [fasthttp](https://github.com/valyala/fasthttp) and [fasthttp/router](https://github.com/fasthttp/router) without loss performance and with a great features.

Look the examples to know how to use it: https://github.com/atreugo/examples

If you need help, open a new issue! 😉
